### ISSUE TITLE
Function on BSD?

### ISSUE THREAD

**Issue by csjjpm** [nymanjens/quizmaster#1]
Hi,
  I am interested in getting quizmaster working on FreeBSD as a service.  Would you have any idea how I could do this?
thank you
Paul

**Comment by nymanjens** [comment]
Hi Paul,

I've never used FreeBSD. Can you run the binary in the release or use the Docker image?

**Comment by csjjpm** [comment]
I'll see if I can get docker running, I can't run the binary as is.  Thank you
