### ISSUE TITLE
Web Interface Does Not Display Correctly In Firefox

### ISSUE THREAD

**Issue by DebugDax** [nymanjens/quizmaster#15]
- Version: 1.151
- Using prebuilt docker
- Using example quiz-config from repo

When browsing the site using Firefox, the pages content does not move to be below the header bar like it does on Chrome. This makes the top line of text get covered.

Firefox (106):
![image](https://user-images.githubusercontent.com/6743505/199645248-b8d3d91b-1afd-44da-a557-997b71a48201.png)

Chrome (107):
![image](https://user-images.githubusercontent.com/6743505/199645272-5ea91d23-c105-4455-83e2-25850f1bee9c.png)

**Comment by nymanjens** [comment]
Hmm, weirdly, I can't reproduce this locally:

![image](https://user-images.githubusercontent.com/2151059/199729077-96357122-bd46-46cf-a9e9-c6d6c791a66f.png)

On my machine, the pages look identical in Chrome and Firefox.

**Comment by DebugDax** [comment]
I'm not sure what resolution you are testing with, but my monitors resolution is 4K (3840 x 2160). Maybe that's the fault here?

If you are using the same, then i'm not sure why my results are different. I tried with Addons disabled to make sure nothing was messing with the CSS and it still hid the text.

**Comment by nymanjens** [comment]
I tested it on my 3840 × 2400 laptop display (probably scaled somehow) and I just tested it on my 2560 × 1440 external monitor, without any issues. I also tried zooming in/out in the browser itself, also without any issues.

**Comment by DebugDax** [comment]
> I tested it on my 3840 × 2400 laptop display (probably scaled somehow) and I just tested it on my 2560 × 1440 external monitor, without any issues. I also tried zooming in/out in the browser itself, also without any issues.

Sorry about the issue request, seems like it was entirely on my end after all.

I had Tamper Monkey add-on set to run in Private Windows so even when I thought I was testing without add-ons, it was still running one. A script inside Tamper Monkey was adjusting the CSS on the page. Disabling it renders the page properly!

Thanks.
