### ISSUE TITLE
Windows 10 22H2 (OS Build 19045.2130) - Error when parsing conf/quiz/quiz-config.yml

### ISSUE THREAD

**Issue by tiborepcek** [nymanjens/quizmaster#16]
Hi and thank you for this great tool!

When I run it on Ubuntu, everything works fine. But on Windows 10 (running cmd as admin) error below appears. File `conf/quiz/quiz-config.yml` is the default one, I did not change it. Could you help me, please? Thanks!

> C:\quizmaster\bin>server.bat
> [info] application - Creating Pool for datasource 'default'
> [info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:h2:mem:inmemorydb
> [error] application - Error when parsing conf/quiz/quiz-config.yml:
> 
> java.nio.file.NoSuchFileException: C:\quizmaster\bin\conf\quiz\quiz-config.yml
>         at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
>         at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
>         at sun.nio.fs.WindowsLinkSupport.getRealPath(Unknown Source)
>         at sun.nio.fs.WindowsPath.toRealPath(Unknown Source)
>         at sun.nio.fs.WindowsPath.toRealPath(Unknown Source)
>         at hydro.common.ResourceFiles$.canonicalizePath(ResourceFiles.scala:35)
>         at app.models.quiz.config.ConfigModule.config(ConfigModule.scala:34)
>         at app.models.quiz.config.ConfigModule$$FastClassByGuice$$399b65b8.invoke(<generated>)
>         at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
>         at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
>         at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
>         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
>         at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:409)
>         at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$3(Injector.scala:118)
>         at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:126)
>         at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:118)
>         at play.api.inject.RoutesProvider.$anonfun$get$2(BuiltinModule.scala:107)
>         at scala.Option.fold(Option.scala:158)
>         at play.api.inject.RoutesProvider.get$lzycompute(BuiltinModule.scala:107)
>         at play.api.inject.RoutesProvider.get(BuiltinModule.scala:103)
>         at play.api.inject.RoutesProvider.get(BuiltinModule.scala:102)
>         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
>         at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
>         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
>         at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
>         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>         at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
>         at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
>         at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
>         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
>         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
>         at com.google.inject.Guice.createInjector(Guice.java:99)
>         at com.google.inject.Guice.createInjector(Guice.java:84)
>         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
>         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
>         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
>         at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
>         at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
>         at play.core.server.ProdServerStart.main(ProdServerStart.scala)
> 
>   Will exit in 1 second due to a failure in conf/quiz/quiz-config.yml

**Comment by nymanjens** [comment]
Are you 100% sure that `C:\quizmaster\bin\conf\quiz\quiz-config.yml` exists on the filesystem?

**Comment by tiborepcek** [comment]
File `C:\quizmaster\conf\quiz\quiz-config.yml` exists. In folder `C:\quizmaster\bin\` there are only these 2 files:

- server
- server.bat

I just unpacked https://github.com/nymanjens/quizmaster/releases/tag/v1.151 to `C:\quizmaster\` folder and I did not change any file.

**Comment by nymanjens** [comment]
Ah I see. The issue is that you should run it from a terminal with current working directory == `C:\quizmaster`
