### ISSUE TITLE
Improve the installation description

### ISSUE THREAD

**Issue by GrimPixel** [nymanjens/quizmaster#18]
Seeing “From prebuilt release in zip file” and “Download the [latest release](https://github.com/nymanjens/quizmaster/releases)”, one may download “Source code (zip)” instead because of that word “zip”. The target users are not necessarily programmers, judging from “Binaries (compiled files)” in “Binaries (compiled files) with demo configuration”

**Comment by nymanjens** [comment]
Fixed
