### ISSUE TITLE
Import/export

### ISSUE THREAD

**Issue by franconianmetal** [nymanjens/quizmaster#19]
How can I export current quiz in order to import after server restart?

**Comment by nymanjens** [comment]
If you look at the standard output in the terminal of the quiz server (the exectuable that starts the quiz), you'll see lines like this appearing:

```
Periodic backup, so you don't lose any data (to paste in master setup page):
<~<-1<~<-1<~<false<~<true<~<Arrows<~<>~>
```

These can be imported in the settings menu:

![image](https://user-images.githubusercontent.com/2151059/230740770-fcac2f2e-1129-4ab6-9ac7-e84e22745ee5.png)

I mainly built this in case something crashes during a quiz to hopefully not lose all progress.
