### ISSUE TITLE
Media missing from Team View

### ISSUE THREAD

**Issue by vinodjam** [nymanjens/quizmaster#2]
Hi,

I was looking to conduct a quiz for a virtual family meet-up this Christmas and I stumbled upon this project in the awesome-selfhosted list. It is really cool and I was able to do almost everything I wanted to pretty easily😃 However I am having some difficulty displaying images/video/audio. I can see the media when I use the master key but not from a teams perspectives in a private window even with the provided example quiz. 

The README mentions "The quiz page: This is the screen to show to all players. It shows the questions, player scores and plays audio and video." but I do not see the player scores/media, only the question and options similar to Carol's view in the sample screenshot where my url contains /app/teamcontroller.

I guess I might be missing something obvious but hopefully you can help me figure out how to display the quiz view to participants too. If there is any other information I can provide that would be helpful, please let me know.

Thank You,
Vinod

**Comment by nymanjens** [comment]
Hi Vinod,

Cool that you found the way to my project :-).

I think there's some confusion about the different views. Copied from the readme:

> 1. The player's answer submission page: This is what players use to input their answers.
> 1. The quiz page: This is the screen to show to all players. It shows the questions, player scores and plays audio and video.
> 1. The master page: This is a screen only for the quizmaster. It allows you to score player answers and generally control the quiz flow.

If you look at the Carol screenshot in the README, the left side is view 2 (quiz page) and the right side is view 1 (player's answer page). If you're doing a virtual quiz, you'll want to share your browser tab that has the quiz page open (view 2). And you'll want to allow the players to connect to your server and use view 1 to fill in the answers.

Note: The master page is optional. It allows you to see/grade the answers while they are being given.

**Comment by vinodjam** [comment]
Ok now I've seen my misunderstanding. Thanks for the quick reply, I'll close the issue
