### ISSUE TITLE
Question visibility

### ISSUE THREAD

**Issue by franconianmetal** [nymanjens/quizmaster#20]
Is it possible to configure that the question is visible on participant"s page?
as well pictures/music snippets if possible?

**Comment by nymanjens** [comment]
Currently, the question is shown by default on the participant's page when they are allowed to enter the answer. Nothing else is shown and none of this is currently configurable.

What is your use case for wanting to extend this?

**Comment by franconianmetal** [comment]
Question is given on participant's page, correct.
but pictures/sound/clips are not.
If pictures were guven would be great.
use case: peoole need to show two windows, one us their answer window, the 2nd is the question window showing the content.

would be fine to present any question content within one window.

or I misunderstood the handing itself

btw: great job on implementation!

**Comment by nymanjens** [comment]
Technically, it's certainly possible to do what you ask, although it would be quite some work to get it to work on all screen sizes.

However, the way this project is supposed to work is that the quizmaster presents their screen and the participants use their phone or a computer only to enter the information. You want to avoid the need for a second screen, but I don't really understand why. Are you organizing a quiz in person or remotely?

**Comment by franconianmetal** [comment]
Both
local/on-site is fine, but for remote will be the case.
But to know how to handle is ok for me. Maybe an extension for later.
Thanks for your details and explanation.
