### ISSUE TITLE
Change NavBar Title?

### ISSUE THREAD

**Issue by JoshMout** [nymanjens/quizmaster#21]
Hi, is there any way to change the title in the top navbar?

![Screenshot 2023-10-23 120248](https://github.com/nymanjens/quizmaster/assets/22785444/9ed4d8c4-47c8-43a9-a6cb-d3858afe82d7)

It's the one thing I can't seem to figure out how to change.

**Comment by nymanjens** [comment]
It's a hard-coded string here: https://github.com/nymanjens/quizmaster/blob/master/app/js/shared/src/main/scala/app/flux/react/app/Layout.scala#L69

You could change it and re-compile the code, or send me a pull request pulling the string into i18n
